title : Abhishek Nagekar's Blog
name: Abhishek Nagekar
description: 'Code, Science, Philosophy, Humor'
meta_description: "Abhishek Nagekar's Blog - Essays on programming, web engineering, security and sometimes life"

markdown: kramdown
highlighter: rouge
logo: false
baseurl: ''
domain_name: 'https://www.nagekar.com'

author:
  name: Abhishek Nagekar

javascript_enabled: true

# Details for the RSS feed generator
url:            'https://www.nagekar.com'

permalink: /:categories/:year/:month/:title.html

collections:
  doodles:
    output: true
    permalink: /doodles/:title.html

featured_posts_title: Unrelated
featured_posts:
  - url: '/2017/02/trip-to-brahmatal-uttarakhand.html'
    title: 'Trek To Bramhatal (Uttarakhand)'
  - url: '/2017/08/privacy.html'
    title: 'Privacy - How I Converted'
  - url: '/2018/01/jagriti-yatra.html'
    title: 'Jagriti Yatra 2017'
  - url: '/2017/08/private-cloud-part-2.html'
    title: 'Private Cloud Part 2 | Encrypted Storage With NextCloud'
  - url: '/2018/07/eli5-how-https-works.html'
    title: 'ELI5 - How HTTPS Works'

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - .jekyll-cache/
  - .idea
  - '*.log'
  - elementary/

plugins:
  - jekyll-sitemap
  - jekyll-feed

remote_theme: abhn/elementary
theme: elementary
